sonar.projectKey=AlejandroAmesticaDuoc_Eva_parcial_2_devops
sonar.organization=alejandroamesticaduoc

sonar.projectName=Eva parcial 2 devops
sonar.projectVersion=1.0

sonar.sources=tienda-tech-backend
sonar.tests=tienda-tech-backend
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=tienda-tech-backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
